name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - uses: stefanoeb/eslint-action@1.0.2
      with:
        files: src/
