name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Install npm
      run: npm install eslint --save-dev
    - name: Install eslint-sarif
      run: npm install @microsoft/eslint-formatter-sarif --save-dev
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
