name: CI
on: push
jobs:
  node_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.JS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm install eslint --save-dev
      - run: npm install @microsoft/eslint-formatter-sarif --save-dev
      - run: npm init @eslint/config
      - run: npx eslint . --ext .js,.jsx,.ts,.tsx -f @microsoft/eslint-formatter-sarif -o result.sarif
