name: CI
on:
  workflow_dispatch:
jobs:
  node_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.JS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm install eslint @microsoft/eslint-formatter-sarif --save

      - run: eslint web-data -f sarif.js -o results.sarif || true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
